# Generated by Django 2.2.9 on 2020-02-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200211_1506'),
        ('books', '0008_auto_20200212_1208'),
    ]

    operations = [
    ]
